version: '3.8'
services:
  node_backend:
    container_name: node_docker
    image: node_docker_image 
    build: 
      context: .
    ports:
      - 5000:5000
    environment:
      - EXTERNAL_PORT=5000
    volumes:
      - ./:/app
