version: '3.8'
services:
  node_backend:
    container_name: node_docker
    image: node_docker_image 
    build: 
      context: .
    ports:
      - 5000:5000
    environment:
      - EXTERNAL_PORT=5000
      - DB_NAME=node_db
      - DB_USER=Danchiwaz 
      - DB_PASSWORD=1234
      - PGHOST=node_db
    volumes:
      - ./:/app
    depends_on:
      - node_db

  node_db:
    container_name: node_db 
    image: postgres:alpine 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=Danchiwaz
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=node_db 
    volumes:
      - pg_volume_db:/var/lib/postgresql/data 

volumes:
  pg_volume_db:
